#!/bin/bash

set -euo pipefail

if ! which pip3 >/dev/null 2>&1 ; then
    echo "pip3 is neede by this script. Install it first."
    exit 1
fi

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
PIP3_TEST_REQUIREMENTS=${SCRIPT_DIR}/requirements-test.txt

pip3 install -r ${PIP3_TEST_REQUIREMENTS} > /dev/null

integration_tests_path="${SCRIPT_DIR}/tests/integration_tests"
unit_tests_path="${SCRIPT_DIR}/tests/unit_tests"

echo "
             _   _                         _            _ _                   _            _       
 _ __  _   _| |_| |__   ___  _ __    _ __ (_)_ __   ___| (_)_ __   ___  ___  | |_ ___  ___| |_ ___ 
| '_ \| | | | __| '_ \ / _ \| '_ \  | '_ \| | '_ \ / _ \ | | '_ \ / _ \/ __| | __/ _ \/ __| __/ __|
| |_) | |_| | |_| | | | (_) | | | | | |_) | | |_) |  __/ | | | | |  __/\__ \ | ||  __/\__ \ |_\__ \\
| .__/ \__, |\__|_| |_|\___/|_| |_| | .__/|_| .__/ \___|_|_|_| |_|\___||___/  \__\___||___/\__|___/
|_|    |___/                        |_|     |_|                                                    

"
echo "==================================================================================================="
echo "Running unit-tests"
unit_tests=$(find ${unit_tests_path} -name *test.py)
coverage run -m unittest ${unit_tests}
# coverage report fails on this as there aren't any results, keep commented out until unittests will be added
# coverage report -m --omit=*tests*

echo "==================================================================================================="
echo "Running integration-tests"
integration_tests=$(find ${integration_tests_path} -name *test.py)
coverage run -m unittest ${integration_tests}
coverage report -m --omit=*tests*