#!/bin/bash

set -euo pipefail

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

integration_tests_path="${SCRIPT_DIR}/tests/integration_tests"
unit_tests_path="${SCRIPT_DIR}/tests/unit_tests"

echo "
             _   _                         _            _ _                   _            _       
 _ __  _   _| |_| |__   ___  _ __    _ __ (_)_ __   ___| (_)_ __   ___  ___  | |_ ___  ___| |_ ___ 
| '_ \| | | | __| '_ \ / _ \| '_ \  | '_ \| | '_ \ / _ \ | | '_ \ / _ \/ __| | __/ _ \/ __| __/ __|
| |_) | |_| | |_| | | | (_) | | | | | |_) | | |_) |  __/ | | | | |  __/\__ \ | ||  __/\__ \ |_\__ \\
| .__/ \__, |\__|_| |_|\___/|_| |_| | .__/|_| .__/ \___|_|_|_| |_|\___||___/  \__\___||___/\__|___/
|_|    |___/                        |_|     |_|                                                    

"
echo "==================================================================================================="
echo "Running unit-tests"
unit_tests=$(find ${unit_tests_path} -name *test.py)
python -m unittest ${unit_tests}

echo "==================================================================================================="
echo "Running integration-tests"
integration_tests=$(find ${integration_tests_path} -name *test.py)
python -m unittest ${integration_tests}