apiVersion: v1
kind: Namespace
metadata:
  name: python-pipelines
---
apiVersion: v1
kind: List
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    name: python-pipelines
    namespace: python-pipelines
  rules:
  - apiGroups: [""]
    resources: ["secrets", "pods/status", "pods/exec"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: python-pipelines
  namespace: python-pipelines
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: python-pipelines
  namespace: python-pipelines
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: python-pipelines
subjects:
- kind: ServiceAccount
  name: python-pipelines
  namespace: python-pipelines
